version: '3.4'

services:
  twosportdb:
    image: nhannq200/two-sport-db-official:1.0
    container_name: two-sport-db-official-container
    environment:
      - SA_PASSWORD=P12345678@
      - ACCEPT_EULA=Y
    ports:
      - "1435:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

  twosportweb:
    image: two-sport-web:1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - twosportdb
    environment:
      DBServer: twosportdb
      DBPort: 1435
      DBDatabase: TwoSportDB
      DBUser: sa
      DBPassword: P12345678@

volumes:
  sqlserverdata:


